// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCManagement.Data;

#nullable disable

namespace SCManagement.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221223184737_DbSetLocation")]
    partial class DbSetLocation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SCManagement.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountyId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountyId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("SCManagement.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Portugal"
                        });
                });

            modelBuilder.Entity("SCManagement.Models.County", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Counties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistrictId = 1,
                            Name = "Águeda"
                        },
                        new
                        {
                            Id = 2,
                            DistrictId = 1,
                            Name = "Albergaria-a-Velha"
                        },
                        new
                        {
                            Id = 3,
                            DistrictId = 1,
                            Name = "Anadia"
                        },
                        new
                        {
                            Id = 4,
                            DistrictId = 1,
                            Name = "Arouca"
                        },
                        new
                        {
                            Id = 5,
                            DistrictId = 1,
                            Name = "Aveiro"
                        },
                        new
                        {
                            Id = 6,
                            DistrictId = 1,
                            Name = "Castelo de Paiva"
                        },
                        new
                        {
                            Id = 7,
                            DistrictId = 1,
                            Name = "Espinho"
                        },
                        new
                        {
                            Id = 8,
                            DistrictId = 1,
                            Name = "Estarreja"
                        },
                        new
                        {
                            Id = 9,
                            DistrictId = 1,
                            Name = "Santa Maria da Feira"
                        },
                        new
                        {
                            Id = 10,
                            DistrictId = 1,
                            Name = "Ílhavo"
                        },
                        new
                        {
                            Id = 11,
                            DistrictId = 1,
                            Name = "Mealhada"
                        },
                        new
                        {
                            Id = 12,
                            DistrictId = 1,
                            Name = "Murtosa"
                        },
                        new
                        {
                            Id = 13,
                            DistrictId = 1,
                            Name = "Oliveira de Azeméis"
                        },
                        new
                        {
                            Id = 14,
                            DistrictId = 1,
                            Name = "Oliveira do Bairro"
                        },
                        new
                        {
                            Id = 15,
                            DistrictId = 1,
                            Name = "Ovar"
                        },
                        new
                        {
                            Id = 16,
                            DistrictId = 1,
                            Name = "São João da Madeira"
                        },
                        new
                        {
                            Id = 17,
                            DistrictId = 1,
                            Name = "Sever do Vouga"
                        },
                        new
                        {
                            Id = 18,
                            DistrictId = 1,
                            Name = "Vagos"
                        },
                        new
                        {
                            Id = 19,
                            DistrictId = 1,
                            Name = "Vale de Cambra"
                        },
                        new
                        {
                            Id = 20,
                            DistrictId = 2,
                            Name = "Aljustrel"
                        },
                        new
                        {
                            Id = 21,
                            DistrictId = 2,
                            Name = "Almodôvar"
                        },
                        new
                        {
                            Id = 22,
                            DistrictId = 2,
                            Name = "Alvito"
                        },
                        new
                        {
                            Id = 23,
                            DistrictId = 2,
                            Name = "Barrancos"
                        },
                        new
                        {
                            Id = 24,
                            DistrictId = 2,
                            Name = "Beja"
                        },
                        new
                        {
                            Id = 25,
                            DistrictId = 2,
                            Name = "Castro Verde"
                        },
                        new
                        {
                            Id = 26,
                            DistrictId = 2,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 27,
                            DistrictId = 2,
                            Name = "Ferreira do Alentejo"
                        },
                        new
                        {
                            Id = 28,
                            DistrictId = 2,
                            Name = "Mértola"
                        },
                        new
                        {
                            Id = 29,
                            DistrictId = 2,
                            Name = "Moura"
                        },
                        new
                        {
                            Id = 30,
                            DistrictId = 2,
                            Name = "Odemira"
                        },
                        new
                        {
                            Id = 31,
                            DistrictId = 2,
                            Name = "Ourique"
                        },
                        new
                        {
                            Id = 32,
                            DistrictId = 2,
                            Name = "Serpa"
                        },
                        new
                        {
                            Id = 33,
                            DistrictId = 2,
                            Name = "Vidigueira"
                        },
                        new
                        {
                            Id = 34,
                            DistrictId = 3,
                            Name = "Amares"
                        },
                        new
                        {
                            Id = 35,
                            DistrictId = 3,
                            Name = "Barcelos"
                        },
                        new
                        {
                            Id = 36,
                            DistrictId = 3,
                            Name = "Braga"
                        },
                        new
                        {
                            Id = 37,
                            DistrictId = 3,
                            Name = "Cabeceiras de Basto"
                        },
                        new
                        {
                            Id = 38,
                            DistrictId = 3,
                            Name = "Celorico de Basto"
                        },
                        new
                        {
                            Id = 39,
                            DistrictId = 3,
                            Name = "Esposende"
                        },
                        new
                        {
                            Id = 40,
                            DistrictId = 3,
                            Name = "Fafe"
                        },
                        new
                        {
                            Id = 41,
                            DistrictId = 3,
                            Name = "Guimarães"
                        },
                        new
                        {
                            Id = 42,
                            DistrictId = 3,
                            Name = "Póvoa de Lanhoso"
                        },
                        new
                        {
                            Id = 43,
                            DistrictId = 3,
                            Name = "Terras de Bouro"
                        },
                        new
                        {
                            Id = 44,
                            DistrictId = 3,
                            Name = "Vieira do Minho"
                        },
                        new
                        {
                            Id = 45,
                            DistrictId = 3,
                            Name = "Vila Nova de Famalicão"
                        },
                        new
                        {
                            Id = 46,
                            DistrictId = 3,
                            Name = "Vila Verde"
                        },
                        new
                        {
                            Id = 47,
                            DistrictId = 3,
                            Name = "Vizela"
                        },
                        new
                        {
                            Id = 48,
                            DistrictId = 4,
                            Name = "Alfândega da Fé"
                        },
                        new
                        {
                            Id = 49,
                            DistrictId = 4,
                            Name = "Bragança"
                        },
                        new
                        {
                            Id = 50,
                            DistrictId = 4,
                            Name = "Carrazeda de Ansiães"
                        },
                        new
                        {
                            Id = 51,
                            DistrictId = 4,
                            Name = "Freixo de Espada à Cinta"
                        },
                        new
                        {
                            Id = 52,
                            DistrictId = 4,
                            Name = "Macedo de Cavaleiros"
                        },
                        new
                        {
                            Id = 53,
                            DistrictId = 4,
                            Name = "Miranda do Douro"
                        },
                        new
                        {
                            Id = 54,
                            DistrictId = 4,
                            Name = "Mirandela"
                        },
                        new
                        {
                            Id = 55,
                            DistrictId = 4,
                            Name = "Mogadouro"
                        },
                        new
                        {
                            Id = 56,
                            DistrictId = 4,
                            Name = "Torre de Moncorvo"
                        },
                        new
                        {
                            Id = 57,
                            DistrictId = 4,
                            Name = "Vila Flor"
                        },
                        new
                        {
                            Id = 58,
                            DistrictId = 4,
                            Name = "Vimioso"
                        },
                        new
                        {
                            Id = 59,
                            DistrictId = 4,
                            Name = "Vinhais"
                        },
                        new
                        {
                            Id = 60,
                            DistrictId = 5,
                            Name = "Belmonte"
                        },
                        new
                        {
                            Id = 61,
                            DistrictId = 5,
                            Name = "Castelo Branco"
                        },
                        new
                        {
                            Id = 62,
                            DistrictId = 5,
                            Name = "Covilhã"
                        },
                        new
                        {
                            Id = 63,
                            DistrictId = 5,
                            Name = "Fundão"
                        },
                        new
                        {
                            Id = 64,
                            DistrictId = 5,
                            Name = "Idanha-a-Nova"
                        },
                        new
                        {
                            Id = 65,
                            DistrictId = 5,
                            Name = "Oleiros"
                        },
                        new
                        {
                            Id = 66,
                            DistrictId = 5,
                            Name = "Penamacor"
                        },
                        new
                        {
                            Id = 67,
                            DistrictId = 5,
                            Name = "Proença-a-Nova"
                        },
                        new
                        {
                            Id = 68,
                            DistrictId = 5,
                            Name = "Sertã"
                        },
                        new
                        {
                            Id = 69,
                            DistrictId = 5,
                            Name = "Vila de Rei"
                        },
                        new
                        {
                            Id = 70,
                            DistrictId = 5,
                            Name = "Vila Velha de Ródão"
                        },
                        new
                        {
                            Id = 71,
                            DistrictId = 6,
                            Name = "Arganil"
                        },
                        new
                        {
                            Id = 72,
                            DistrictId = 6,
                            Name = "Cantanhede"
                        },
                        new
                        {
                            Id = 73,
                            DistrictId = 6,
                            Name = "Coimbra"
                        },
                        new
                        {
                            Id = 74,
                            DistrictId = 6,
                            Name = "Condeixa-a-Nova"
                        },
                        new
                        {
                            Id = 75,
                            DistrictId = 6,
                            Name = "Figueira da Foz"
                        },
                        new
                        {
                            Id = 76,
                            DistrictId = 6,
                            Name = "Góis"
                        },
                        new
                        {
                            Id = 77,
                            DistrictId = 6,
                            Name = "Lousã"
                        },
                        new
                        {
                            Id = 78,
                            DistrictId = 6,
                            Name = "Mira"
                        },
                        new
                        {
                            Id = 79,
                            DistrictId = 6,
                            Name = "Miranda do Corvo"
                        },
                        new
                        {
                            Id = 80,
                            DistrictId = 6,
                            Name = "Montemor-o-Velho"
                        },
                        new
                        {
                            Id = 81,
                            DistrictId = 6,
                            Name = "Oliveira do Hospital"
                        },
                        new
                        {
                            Id = 82,
                            DistrictId = 6,
                            Name = "Pampilhosa da Serra"
                        },
                        new
                        {
                            Id = 83,
                            DistrictId = 6,
                            Name = "Penacova"
                        },
                        new
                        {
                            Id = 84,
                            DistrictId = 6,
                            Name = "Penela"
                        },
                        new
                        {
                            Id = 85,
                            DistrictId = 6,
                            Name = "Soure"
                        },
                        new
                        {
                            Id = 86,
                            DistrictId = 6,
                            Name = "Tábua"
                        },
                        new
                        {
                            Id = 87,
                            DistrictId = 6,
                            Name = "Vila Nova de Poiares"
                        },
                        new
                        {
                            Id = 88,
                            DistrictId = 7,
                            Name = "Alandroal"
                        },
                        new
                        {
                            Id = 89,
                            DistrictId = 7,
                            Name = "Arraiolos"
                        },
                        new
                        {
                            Id = 90,
                            DistrictId = 7,
                            Name = "Borba"
                        },
                        new
                        {
                            Id = 91,
                            DistrictId = 7,
                            Name = "Estremoz"
                        },
                        new
                        {
                            Id = 92,
                            DistrictId = 7,
                            Name = "Évora"
                        },
                        new
                        {
                            Id = 93,
                            DistrictId = 7,
                            Name = "Montemor-o-Novo"
                        },
                        new
                        {
                            Id = 94,
                            DistrictId = 7,
                            Name = "Mora"
                        },
                        new
                        {
                            Id = 95,
                            DistrictId = 7,
                            Name = "Mourão"
                        },
                        new
                        {
                            Id = 96,
                            DistrictId = 7,
                            Name = "Portel"
                        },
                        new
                        {
                            Id = 97,
                            DistrictId = 7,
                            Name = "Redondo"
                        },
                        new
                        {
                            Id = 98,
                            DistrictId = 7,
                            Name = "Reguengos de Monsaraz"
                        },
                        new
                        {
                            Id = 99,
                            DistrictId = 7,
                            Name = "Vendas Novas"
                        },
                        new
                        {
                            Id = 100,
                            DistrictId = 7,
                            Name = "Viana do Alentejo"
                        },
                        new
                        {
                            Id = 101,
                            DistrictId = 7,
                            Name = "Vila Viçosa"
                        },
                        new
                        {
                            Id = 102,
                            DistrictId = 8,
                            Name = "Albufeira"
                        },
                        new
                        {
                            Id = 103,
                            DistrictId = 8,
                            Name = "Alcoutim"
                        },
                        new
                        {
                            Id = 104,
                            DistrictId = 8,
                            Name = "Aljezur"
                        },
                        new
                        {
                            Id = 105,
                            DistrictId = 8,
                            Name = "Castro Marim"
                        },
                        new
                        {
                            Id = 106,
                            DistrictId = 8,
                            Name = "Faro"
                        },
                        new
                        {
                            Id = 107,
                            DistrictId = 8,
                            Name = "Lagoa"
                        },
                        new
                        {
                            Id = 108,
                            DistrictId = 8,
                            Name = "Lagos"
                        },
                        new
                        {
                            Id = 109,
                            DistrictId = 8,
                            Name = "Loulé"
                        },
                        new
                        {
                            Id = 110,
                            DistrictId = 8,
                            Name = "Monchique"
                        },
                        new
                        {
                            Id = 111,
                            DistrictId = 8,
                            Name = "Olhão"
                        },
                        new
                        {
                            Id = 112,
                            DistrictId = 8,
                            Name = "Portimão"
                        },
                        new
                        {
                            Id = 113,
                            DistrictId = 8,
                            Name = "São Brás de Alportel"
                        },
                        new
                        {
                            Id = 114,
                            DistrictId = 8,
                            Name = "Silves"
                        },
                        new
                        {
                            Id = 115,
                            DistrictId = 8,
                            Name = "Tavira"
                        },
                        new
                        {
                            Id = 116,
                            DistrictId = 8,
                            Name = "Vila do Bispo"
                        },
                        new
                        {
                            Id = 117,
                            DistrictId = 8,
                            Name = "Vila Real de Santo António"
                        },
                        new
                        {
                            Id = 118,
                            DistrictId = 9,
                            Name = "Aguiar da Beira"
                        },
                        new
                        {
                            Id = 119,
                            DistrictId = 9,
                            Name = "Almeida"
                        },
                        new
                        {
                            Id = 120,
                            DistrictId = 9,
                            Name = "Celorico da Beira"
                        },
                        new
                        {
                            Id = 121,
                            DistrictId = 9,
                            Name = "Figueira de Castelo Rodrigo"
                        },
                        new
                        {
                            Id = 122,
                            DistrictId = 9,
                            Name = "Fornos de Algodres"
                        },
                        new
                        {
                            Id = 123,
                            DistrictId = 9,
                            Name = "Gouveia"
                        },
                        new
                        {
                            Id = 124,
                            DistrictId = 9,
                            Name = "Guarda"
                        },
                        new
                        {
                            Id = 125,
                            DistrictId = 9,
                            Name = "Manteigas"
                        },
                        new
                        {
                            Id = 126,
                            DistrictId = 9,
                            Name = "Mêda"
                        },
                        new
                        {
                            Id = 127,
                            DistrictId = 9,
                            Name = "Pinhel"
                        },
                        new
                        {
                            Id = 128,
                            DistrictId = 9,
                            Name = "Sabugal"
                        },
                        new
                        {
                            Id = 129,
                            DistrictId = 9,
                            Name = "Seia"
                        },
                        new
                        {
                            Id = 130,
                            DistrictId = 9,
                            Name = "Trancoso"
                        },
                        new
                        {
                            Id = 131,
                            DistrictId = 9,
                            Name = "Vila Nova de Foz Côa"
                        },
                        new
                        {
                            Id = 132,
                            DistrictId = 10,
                            Name = "Alcobaça"
                        },
                        new
                        {
                            Id = 133,
                            DistrictId = 10,
                            Name = "Alvaiázere"
                        },
                        new
                        {
                            Id = 134,
                            DistrictId = 10,
                            Name = "Ansião"
                        },
                        new
                        {
                            Id = 135,
                            DistrictId = 10,
                            Name = "Batalha"
                        },
                        new
                        {
                            Id = 136,
                            DistrictId = 10,
                            Name = "Bombarral"
                        },
                        new
                        {
                            Id = 137,
                            DistrictId = 10,
                            Name = "Caldas da Rainha"
                        },
                        new
                        {
                            Id = 138,
                            DistrictId = 10,
                            Name = "Castanheira de Pêra"
                        },
                        new
                        {
                            Id = 139,
                            DistrictId = 10,
                            Name = "Figueiró dos Vinhos"
                        },
                        new
                        {
                            Id = 140,
                            DistrictId = 10,
                            Name = "Leiria"
                        },
                        new
                        {
                            Id = 141,
                            DistrictId = 10,
                            Name = "Marinha Grande"
                        },
                        new
                        {
                            Id = 142,
                            DistrictId = 10,
                            Name = "Nazaré"
                        },
                        new
                        {
                            Id = 143,
                            DistrictId = 10,
                            Name = "Óbidos"
                        },
                        new
                        {
                            Id = 144,
                            DistrictId = 10,
                            Name = "Pedrógão Grande"
                        },
                        new
                        {
                            Id = 145,
                            DistrictId = 10,
                            Name = "Peniche"
                        },
                        new
                        {
                            Id = 146,
                            DistrictId = 10,
                            Name = "Pombal"
                        },
                        new
                        {
                            Id = 147,
                            DistrictId = 10,
                            Name = "Porto de Mós"
                        },
                        new
                        {
                            Id = 148,
                            DistrictId = 11,
                            Name = "Alenquer"
                        },
                        new
                        {
                            Id = 149,
                            DistrictId = 11,
                            Name = "Arruda dos Vinhos"
                        },
                        new
                        {
                            Id = 150,
                            DistrictId = 11,
                            Name = "Azambuja"
                        },
                        new
                        {
                            Id = 151,
                            DistrictId = 11,
                            Name = "Cadaval"
                        },
                        new
                        {
                            Id = 152,
                            DistrictId = 11,
                            Name = "Cascais"
                        },
                        new
                        {
                            Id = 153,
                            DistrictId = 11,
                            Name = "Lisboa"
                        },
                        new
                        {
                            Id = 154,
                            DistrictId = 11,
                            Name = "Loures"
                        },
                        new
                        {
                            Id = 155,
                            DistrictId = 11,
                            Name = "Lourinhã"
                        },
                        new
                        {
                            Id = 156,
                            DistrictId = 11,
                            Name = "Mafra"
                        },
                        new
                        {
                            Id = 157,
                            DistrictId = 11,
                            Name = "Oeiras"
                        },
                        new
                        {
                            Id = 158,
                            DistrictId = 11,
                            Name = "Sintra"
                        },
                        new
                        {
                            Id = 159,
                            DistrictId = 11,
                            Name = "Sobral de Monte Agraço"
                        },
                        new
                        {
                            Id = 160,
                            DistrictId = 11,
                            Name = "Torres Vedras"
                        },
                        new
                        {
                            Id = 161,
                            DistrictId = 11,
                            Name = "Vila Franca de Xira"
                        },
                        new
                        {
                            Id = 162,
                            DistrictId = 11,
                            Name = "Amadora"
                        },
                        new
                        {
                            Id = 163,
                            DistrictId = 11,
                            Name = "Odivelas"
                        },
                        new
                        {
                            Id = 164,
                            DistrictId = 12,
                            Name = "Alter do Chão"
                        },
                        new
                        {
                            Id = 165,
                            DistrictId = 12,
                            Name = "Arronches"
                        },
                        new
                        {
                            Id = 166,
                            DistrictId = 12,
                            Name = "Avis"
                        },
                        new
                        {
                            Id = 167,
                            DistrictId = 12,
                            Name = "Campo Maior"
                        },
                        new
                        {
                            Id = 168,
                            DistrictId = 12,
                            Name = "Castelo de Vide"
                        },
                        new
                        {
                            Id = 169,
                            DistrictId = 12,
                            Name = "Crato"
                        },
                        new
                        {
                            Id = 170,
                            DistrictId = 12,
                            Name = "Elvas"
                        },
                        new
                        {
                            Id = 171,
                            DistrictId = 12,
                            Name = "Fronteira"
                        },
                        new
                        {
                            Id = 172,
                            DistrictId = 12,
                            Name = "Gavião"
                        },
                        new
                        {
                            Id = 173,
                            DistrictId = 12,
                            Name = "Marvão"
                        },
                        new
                        {
                            Id = 174,
                            DistrictId = 12,
                            Name = "Monforte"
                        },
                        new
                        {
                            Id = 175,
                            DistrictId = 12,
                            Name = "Nisa"
                        },
                        new
                        {
                            Id = 176,
                            DistrictId = 12,
                            Name = "Ponte de Sor"
                        },
                        new
                        {
                            Id = 177,
                            DistrictId = 12,
                            Name = "Portalegre"
                        },
                        new
                        {
                            Id = 178,
                            DistrictId = 12,
                            Name = "Sousel"
                        },
                        new
                        {
                            Id = 179,
                            DistrictId = 13,
                            Name = "Amarante"
                        },
                        new
                        {
                            Id = 180,
                            DistrictId = 13,
                            Name = "Baião"
                        },
                        new
                        {
                            Id = 181,
                            DistrictId = 13,
                            Name = "Felgueiras"
                        },
                        new
                        {
                            Id = 182,
                            DistrictId = 13,
                            Name = "Gondomar"
                        },
                        new
                        {
                            Id = 183,
                            DistrictId = 13,
                            Name = "Lousada"
                        },
                        new
                        {
                            Id = 184,
                            DistrictId = 13,
                            Name = "Maia"
                        },
                        new
                        {
                            Id = 185,
                            DistrictId = 13,
                            Name = "Marco de Canaveses"
                        },
                        new
                        {
                            Id = 186,
                            DistrictId = 13,
                            Name = "Matosinhos"
                        },
                        new
                        {
                            Id = 187,
                            DistrictId = 13,
                            Name = "Paços de Ferreira"
                        },
                        new
                        {
                            Id = 188,
                            DistrictId = 13,
                            Name = "Paredes"
                        },
                        new
                        {
                            Id = 189,
                            DistrictId = 13,
                            Name = "Penafiel"
                        },
                        new
                        {
                            Id = 190,
                            DistrictId = 13,
                            Name = "Porto"
                        },
                        new
                        {
                            Id = 191,
                            DistrictId = 13,
                            Name = "Póvoa de Varzim"
                        },
                        new
                        {
                            Id = 192,
                            DistrictId = 13,
                            Name = "Santo Tirso"
                        },
                        new
                        {
                            Id = 193,
                            DistrictId = 13,
                            Name = "Valongo"
                        },
                        new
                        {
                            Id = 194,
                            DistrictId = 13,
                            Name = "Vila do Conde"
                        },
                        new
                        {
                            Id = 195,
                            DistrictId = 13,
                            Name = "Vila Nova de Gaia"
                        },
                        new
                        {
                            Id = 196,
                            DistrictId = 13,
                            Name = "Trofa"
                        },
                        new
                        {
                            Id = 197,
                            DistrictId = 14,
                            Name = "Abrantes"
                        },
                        new
                        {
                            Id = 198,
                            DistrictId = 14,
                            Name = "Alcanena"
                        },
                        new
                        {
                            Id = 199,
                            DistrictId = 14,
                            Name = "Almeirim"
                        },
                        new
                        {
                            Id = 200,
                            DistrictId = 14,
                            Name = "Alpiarça"
                        },
                        new
                        {
                            Id = 201,
                            DistrictId = 14,
                            Name = "Benavente"
                        },
                        new
                        {
                            Id = 202,
                            DistrictId = 14,
                            Name = "Cartaxo"
                        },
                        new
                        {
                            Id = 203,
                            DistrictId = 14,
                            Name = "Chamusca"
                        },
                        new
                        {
                            Id = 204,
                            DistrictId = 14,
                            Name = "Constância"
                        },
                        new
                        {
                            Id = 205,
                            DistrictId = 14,
                            Name = "Coruche"
                        },
                        new
                        {
                            Id = 206,
                            DistrictId = 14,
                            Name = "Entroncamento"
                        },
                        new
                        {
                            Id = 207,
                            DistrictId = 14,
                            Name = "Ferreira do Zêzere"
                        },
                        new
                        {
                            Id = 208,
                            DistrictId = 14,
                            Name = "Golegã"
                        },
                        new
                        {
                            Id = 209,
                            DistrictId = 14,
                            Name = "Mação"
                        },
                        new
                        {
                            Id = 210,
                            DistrictId = 14,
                            Name = "Rio Maior"
                        },
                        new
                        {
                            Id = 211,
                            DistrictId = 14,
                            Name = "Salvaterra de Magos"
                        },
                        new
                        {
                            Id = 212,
                            DistrictId = 14,
                            Name = "Santarém"
                        },
                        new
                        {
                            Id = 213,
                            DistrictId = 14,
                            Name = "Sardoal"
                        },
                        new
                        {
                            Id = 214,
                            DistrictId = 14,
                            Name = "Tomar"
                        },
                        new
                        {
                            Id = 215,
                            DistrictId = 14,
                            Name = "Torres Novas"
                        },
                        new
                        {
                            Id = 216,
                            DistrictId = 14,
                            Name = "Vila Nova da Barquinha"
                        },
                        new
                        {
                            Id = 217,
                            DistrictId = 14,
                            Name = "Ourém"
                        },
                        new
                        {
                            Id = 218,
                            DistrictId = 15,
                            Name = "Alcácer do Sal"
                        },
                        new
                        {
                            Id = 219,
                            DistrictId = 15,
                            Name = "Alcochete"
                        },
                        new
                        {
                            Id = 220,
                            DistrictId = 15,
                            Name = "Almada"
                        },
                        new
                        {
                            Id = 221,
                            DistrictId = 15,
                            Name = "Barreiro"
                        },
                        new
                        {
                            Id = 222,
                            DistrictId = 15,
                            Name = "Grândola"
                        },
                        new
                        {
                            Id = 223,
                            DistrictId = 15,
                            Name = "Moita"
                        },
                        new
                        {
                            Id = 224,
                            DistrictId = 15,
                            Name = "Montijo"
                        },
                        new
                        {
                            Id = 225,
                            DistrictId = 15,
                            Name = "Palmela"
                        },
                        new
                        {
                            Id = 226,
                            DistrictId = 15,
                            Name = "Santiago do Cacém"
                        },
                        new
                        {
                            Id = 227,
                            DistrictId = 15,
                            Name = "Seixal"
                        },
                        new
                        {
                            Id = 228,
                            DistrictId = 15,
                            Name = "Sesimbra"
                        },
                        new
                        {
                            Id = 229,
                            DistrictId = 15,
                            Name = "Setúbal"
                        },
                        new
                        {
                            Id = 230,
                            DistrictId = 15,
                            Name = "Sines"
                        },
                        new
                        {
                            Id = 231,
                            DistrictId = 16,
                            Name = "Arcos de Valdevez"
                        },
                        new
                        {
                            Id = 232,
                            DistrictId = 16,
                            Name = "Caminha"
                        },
                        new
                        {
                            Id = 233,
                            DistrictId = 16,
                            Name = "Melgaço"
                        },
                        new
                        {
                            Id = 234,
                            DistrictId = 16,
                            Name = "Monção"
                        },
                        new
                        {
                            Id = 235,
                            DistrictId = 16,
                            Name = "Paredes de Coura"
                        },
                        new
                        {
                            Id = 236,
                            DistrictId = 16,
                            Name = "Ponte da Barca"
                        },
                        new
                        {
                            Id = 237,
                            DistrictId = 16,
                            Name = "Ponte de Lima"
                        },
                        new
                        {
                            Id = 238,
                            DistrictId = 16,
                            Name = "Valença"
                        },
                        new
                        {
                            Id = 239,
                            DistrictId = 16,
                            Name = "Viana do Castelo"
                        },
                        new
                        {
                            Id = 240,
                            DistrictId = 16,
                            Name = "Vila Nova de Cerveira"
                        },
                        new
                        {
                            Id = 241,
                            DistrictId = 17,
                            Name = "Alijó"
                        },
                        new
                        {
                            Id = 242,
                            DistrictId = 17,
                            Name = "Boticas"
                        },
                        new
                        {
                            Id = 243,
                            DistrictId = 17,
                            Name = "Chaves"
                        },
                        new
                        {
                            Id = 244,
                            DistrictId = 17,
                            Name = "Mesão Frio"
                        },
                        new
                        {
                            Id = 245,
                            DistrictId = 17,
                            Name = "Mondim de Basto"
                        },
                        new
                        {
                            Id = 246,
                            DistrictId = 17,
                            Name = "Montalegre"
                        },
                        new
                        {
                            Id = 247,
                            DistrictId = 17,
                            Name = "Murça"
                        },
                        new
                        {
                            Id = 248,
                            DistrictId = 17,
                            Name = "Peso da Régua"
                        },
                        new
                        {
                            Id = 249,
                            DistrictId = 17,
                            Name = "Ribeira de Pena"
                        },
                        new
                        {
                            Id = 250,
                            DistrictId = 17,
                            Name = "Sabrosa"
                        },
                        new
                        {
                            Id = 251,
                            DistrictId = 17,
                            Name = "Santa Marta de Penaguião"
                        },
                        new
                        {
                            Id = 252,
                            DistrictId = 17,
                            Name = "Valpaços"
                        },
                        new
                        {
                            Id = 253,
                            DistrictId = 17,
                            Name = "Vila Pouca de Aguiar"
                        },
                        new
                        {
                            Id = 254,
                            DistrictId = 17,
                            Name = "Vila Real"
                        },
                        new
                        {
                            Id = 255,
                            DistrictId = 18,
                            Name = "Armamar"
                        },
                        new
                        {
                            Id = 256,
                            DistrictId = 18,
                            Name = "Carregal do Sal"
                        },
                        new
                        {
                            Id = 257,
                            DistrictId = 18,
                            Name = "Castro Daire"
                        },
                        new
                        {
                            Id = 258,
                            DistrictId = 18,
                            Name = "Cinfães"
                        },
                        new
                        {
                            Id = 259,
                            DistrictId = 18,
                            Name = "Lamego"
                        },
                        new
                        {
                            Id = 260,
                            DistrictId = 18,
                            Name = "Mangualde"
                        },
                        new
                        {
                            Id = 261,
                            DistrictId = 18,
                            Name = "Moimenta da Beira"
                        },
                        new
                        {
                            Id = 262,
                            DistrictId = 18,
                            Name = "Mortágua"
                        },
                        new
                        {
                            Id = 263,
                            DistrictId = 18,
                            Name = "Nelas"
                        },
                        new
                        {
                            Id = 264,
                            DistrictId = 18,
                            Name = "Oliveira de Frades"
                        },
                        new
                        {
                            Id = 265,
                            DistrictId = 18,
                            Name = "Penalva do Castelo"
                        },
                        new
                        {
                            Id = 266,
                            DistrictId = 18,
                            Name = "Penedono"
                        },
                        new
                        {
                            Id = 267,
                            DistrictId = 18,
                            Name = "Resende"
                        },
                        new
                        {
                            Id = 268,
                            DistrictId = 18,
                            Name = "Santa Comba Dão"
                        },
                        new
                        {
                            Id = 269,
                            DistrictId = 18,
                            Name = "São João da Pesqueira"
                        },
                        new
                        {
                            Id = 270,
                            DistrictId = 18,
                            Name = "São Pedro do Sul"
                        },
                        new
                        {
                            Id = 271,
                            DistrictId = 18,
                            Name = "Sátão"
                        },
                        new
                        {
                            Id = 272,
                            DistrictId = 18,
                            Name = "Sernancelhe"
                        },
                        new
                        {
                            Id = 273,
                            DistrictId = 18,
                            Name = "Tabuaço"
                        },
                        new
                        {
                            Id = 274,
                            DistrictId = 18,
                            Name = "Tarouca"
                        },
                        new
                        {
                            Id = 275,
                            DistrictId = 18,
                            Name = "Tondela"
                        },
                        new
                        {
                            Id = 276,
                            DistrictId = 18,
                            Name = "Vila Nova de Paiva"
                        },
                        new
                        {
                            Id = 277,
                            DistrictId = 18,
                            Name = "Viseu"
                        },
                        new
                        {
                            Id = 278,
                            DistrictId = 18,
                            Name = "Vouzela"
                        },
                        new
                        {
                            Id = 279,
                            DistrictId = 19,
                            Name = "Calheta"
                        },
                        new
                        {
                            Id = 280,
                            DistrictId = 19,
                            Name = "Câmara de Lobos"
                        },
                        new
                        {
                            Id = 281,
                            DistrictId = 19,
                            Name = "Funchal"
                        },
                        new
                        {
                            Id = 282,
                            DistrictId = 19,
                            Name = "Machico"
                        },
                        new
                        {
                            Id = 283,
                            DistrictId = 19,
                            Name = "Ponta do Sol"
                        },
                        new
                        {
                            Id = 284,
                            DistrictId = 19,
                            Name = "Porto Moniz"
                        },
                        new
                        {
                            Id = 285,
                            DistrictId = 19,
                            Name = "Ribeira Brava"
                        },
                        new
                        {
                            Id = 286,
                            DistrictId = 19,
                            Name = "Santa Cruz"
                        },
                        new
                        {
                            Id = 287,
                            DistrictId = 19,
                            Name = "Santana"
                        },
                        new
                        {
                            Id = 288,
                            DistrictId = 19,
                            Name = "São Vicente"
                        },
                        new
                        {
                            Id = 289,
                            DistrictId = 20,
                            Name = "Porto Santo"
                        },
                        new
                        {
                            Id = 290,
                            DistrictId = 21,
                            Name = "Vila do Porto"
                        },
                        new
                        {
                            Id = 291,
                            DistrictId = 22,
                            Name = "Lagoa"
                        },
                        new
                        {
                            Id = 292,
                            DistrictId = 22,
                            Name = "Nordeste"
                        },
                        new
                        {
                            Id = 293,
                            DistrictId = 22,
                            Name = "Ponta Delgada"
                        },
                        new
                        {
                            Id = 294,
                            DistrictId = 22,
                            Name = "Povoação"
                        },
                        new
                        {
                            Id = 295,
                            DistrictId = 22,
                            Name = "Ribeira Grande"
                        },
                        new
                        {
                            Id = 296,
                            DistrictId = 22,
                            Name = "Vila Franca do Campo"
                        },
                        new
                        {
                            Id = 297,
                            DistrictId = 23,
                            Name = "Angra do Heroísmo"
                        },
                        new
                        {
                            Id = 298,
                            DistrictId = 23,
                            Name = "Vila da Praia da Vitória"
                        },
                        new
                        {
                            Id = 299,
                            DistrictId = 24,
                            Name = "Santa Cruz da Graciosa"
                        },
                        new
                        {
                            Id = 300,
                            DistrictId = 25,
                            Name = "Calheta"
                        },
                        new
                        {
                            Id = 301,
                            DistrictId = 25,
                            Name = "Velas"
                        },
                        new
                        {
                            Id = 302,
                            DistrictId = 26,
                            Name = "Lajes do Pico"
                        },
                        new
                        {
                            Id = 303,
                            DistrictId = 26,
                            Name = "Madalena"
                        },
                        new
                        {
                            Id = 304,
                            DistrictId = 26,
                            Name = "São Roque do Pico"
                        },
                        new
                        {
                            Id = 305,
                            DistrictId = 27,
                            Name = "Horta"
                        },
                        new
                        {
                            Id = 306,
                            DistrictId = 28,
                            Name = "Lajes das Flores"
                        },
                        new
                        {
                            Id = 307,
                            DistrictId = 28,
                            Name = "Santa Cruz das Flores"
                        },
                        new
                        {
                            Id = 308,
                            DistrictId = 29,
                            Name = "Corvo"
                        });
                });

            modelBuilder.Entity("SCManagement.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Aveiro"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Beja"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Braga"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            Name = "Bragança"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            Name = "Castelo Branco"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            Name = "Coimbra"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 1,
                            Name = "Évora"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 1,
                            Name = "Faro"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 1,
                            Name = "Guarda"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 1,
                            Name = "Leiria"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 1,
                            Name = "Lisboa"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 1,
                            Name = "Portalegre"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 1,
                            Name = "Porto"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 1,
                            Name = "Santarém"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 1,
                            Name = "Setúbal"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 1,
                            Name = "Viana do Castelo"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 1,
                            Name = "Vila Real"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 1,
                            Name = "Viseu"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 1,
                            Name = "Ilha da Madeira"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 1,
                            Name = "Ilha de Porto Santo"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 1,
                            Name = "Ilha de Santa Maria"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 1,
                            Name = "Ilha de São Miguel"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 1,
                            Name = "Ilha Terceira"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 1,
                            Name = "Ilha Graciosa"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 1,
                            Name = "Ilha de São Jorge"
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 1,
                            Name = "Ilha do Pico"
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 1,
                            Name = "Ilha do Faial"
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 1,
                            Name = "Ilha das Flores"
                        },
                        new
                        {
                            Id = 29,
                            CountryId = 1,
                            Name = "Ilha do Corvo"
                        });
                });

            modelBuilder.Entity("SCManagement.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SCManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SCManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SCManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SCManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SCManagement.Models.Address", b =>
                {
                    b.HasOne("SCManagement.Models.County", "County")
                        .WithMany()
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("County");
                });

            modelBuilder.Entity("SCManagement.Models.County", b =>
                {
                    b.HasOne("SCManagement.Models.District", "District")
                        .WithMany("Counties")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("SCManagement.Models.District", b =>
                {
                    b.HasOne("SCManagement.Models.Country", "Country")
                        .WithMany("Districts")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SCManagement.Models.User", b =>
                {
                    b.HasOne("SCManagement.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("SCManagement.Models.Country", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("SCManagement.Models.District", b =>
                {
                    b.Navigation("Counties");
                });
#pragma warning restore 612, 618
        }
    }
}
